apiVersion: v1
kind: ResourceQuota
metadata:
  name: modular-monolith-quota
  namespace: modular-monolith
  labels:
    app.kubernetes.io/name: modular-monolith
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "1Gi"
    limits.cpu: "2"
    limits.memory: "2Gi"
    pods: "5"