apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-shared-storage
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /data/k8s-pv # Evitar /tmp pois é efêmero