apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-postgre-pvc
  namespace: modular-monolith
  labels:
    app.kubernetes.io/name: modular-monolith
    app.kubernetes.io/component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path