apiVersion: v1
kind: LimitRange
metadata:
  name: modular-monolith-limits
  namespace: modular-monolith
  labels:
    app.kubernetes.io/name: modular-monolith
spec:
  limits:
    - default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "200m"
        memory: "256Mi"
      type: Container