apiVersion: v1
kind: Namespace
metadata:
  name: modular-monolith
  annotations:
    description: "Namespace principal do ERP modular monolith"
  labels:
    app.kubernetes.io/name: modular-monolith
    environment: dev