apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: erp-modular-ingress
  namespace: modular-monolith
  labels:
    app.kubernetes.io/name: modular-monolith
    app.kubernetes.io/component: ingress
spec:
  ingressClassName: nginx
  rules:
    - host: erp-monolith.local # Domínio customizado, adicione no /etc/hosts(linux) apontando para o IP do Minikube
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: modular-monolith
                port:
                  number: 3000
