apiVersion: v1
kind: Namespace
metadata:
  name: auth-worker
  annotations:
    description: "Namespace do worker de autenticação"
  labels:
    app.kubernetes.io/name: auth-worker
    environment: dev