apiVersion: v1
kind: ConfigMap
metadata:
  name: modular-monolith-config
  namespace: modular-monolith
  labels:
    app.kubernetes.io/name: modular-monolith
data:
  NODE_PORT: "3000"
  NODE_ENV: "local"

  # RabbitMQ
  AMQP_EXCHANGE: "erp.exchange"

  # Postgres
  POSTGRES_HOST: "host.minikube.internal"
  POSTGRES_PORT: "5432"

  # Logging
  LOGGING: ""

  # AWS
  AWS_REGION: "us-east-1"
  BUCKET_NAME: "meu-bucket-local"
  AWS_S3_ENDPOINT: "http://host.minikube.internal:4566"
  S3_PREFIX: "erp"
